#
# COPYRIGHT Ericsson 2024
#
# The copyright to the computer program(s) herein is the property of
# Ericsson Inc. The programs may be used and/or copied only with written
# permission from Ericsson Inc. or in accordance with the terms and
# conditions stipulated in the agreement/contract under which the
# program(s) have been supplied.
#

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "eric-oss-pm-stats-calculator.name" . }}-jmx-logging-properties
  labels:
{{ include "eric-oss-pm-stats-calculator.labels" . | indent 4 }}
  annotations:
{{ include "eric-oss-pm-stats-calculator.annotations" . | indent 4 }}
data:
  logging.properties: |-
{{- .Values.jmxExporter.debug.javaLoggingProperties | nindent 4 -}}
