#
# COPYRIGHT Ericsson 2024
#
# The copyright to the computer program(s) herein is the property of
# Ericsson Inc. The programs may be used and/or copied only with written
# permission from Ericsson Inc. or in accordance with the terms and
# conditions stipulated in the agreement/contract under which the
# program(s) have been supplied.
#

{{- if .Values.cnom.enabled }}
{{- $calculatorName := include "eric-oss-pm-stats-calculator.name" . }}
{{- $podLabel := include "eric-oss-pm-stats-calculator.cnom-pod-label" . }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "eric-oss-pm-stats-calculator.name" . }}-cnom-system-red-config
  labels:
{{- include "eric-oss-pm-stats-calculator.labels" . | nindent 4 }}
{{- include "eric-oss-pm-stats-calculator.cnom-labels" . | nindent 4 }}
  annotations:
{{- include "eric-oss-pm-stats-calculator.annotations" . | nindent 4 }}
data:
  cnom-system-red-metrics-config.json: |-
    {
      "namespace": "PMH_PMSC_SYSTEM_RED_{{ $calculatorName | replace "-" "_" | upper }}",
      "dashboards": [
        {
          "_id": "{{ .Release.Name | replace "-" "_" }}_red_metrics",
          "title": "PM Stats Calculator RED Metrics",
          "apps": ["statusOverview"],
          "order": 0,
          "dashboardTreeView": {
            "tree": [["PM Stats Calculation Handling", "PM Stats Calculator", "RED metrics"]]
          },
          "tiles": [
            {
              "xSize": 5,
              "widget": "avg_http_response_latency"
            },
            {
              "xSize": 5,
              "widget": "longest_http_response_latency"
            },
            {
              "xSize": 5,
              "widget": "longest_pm_stats_calculator_api_definition_post_endpoint_duration"
            },
            {
              "xSize": 5,
              "widget": "longest_pm_stats_calculator_api_definition_delete_endpoint_duration"
            },
            {
              "xSize": 5,
              "widget": "longest_pm_stats_calculator_api_definition_patch_endpoint_duration"
            },
            {
              "xSize": 5,
              "widget": "longest_pm_stats_calculator_api_definition_get_endpoint_duration"
            },
            {
              "xSize": 5,
              "widget": "widget_timeline_http_server_requests_seconds_count"
            },
            {
              "xSize": 5,
              "widget": "widget_timeline_http_server_requests_seconds_max"
            },
            {
              "xSize": 5,
              "widget": "widget_timeline_http_server_requests_seconds_sum"
            }
          ]
        }
      ],
      "widgets": [
        {
          "_id": "avg_http_response_latency",
          "widgetType": "timeline",
          "title": "Average HTTP response latency",
          "unit": "milliseconds",
          "sources": [
            {
              "source": "avg_http_response_latency"
            }
          ]
        },
        {
          "_id": "longest_http_response_latency",
          "widgetType": "timeline",
          "title": "Max HTTP response latency",
          "unit": "milliseconds",
          "sources": [
            {
              "source": "longest_http_response_latency"
            }
          ]
        },
        {
          "_id": "longest_pm_stats_calculator_api_definition_post_endpoint_duration",
          "widgetType": "timeline",
          "title": "Max KPI POST endpoint duration",
          "unit": "milliseconds",
          "sources": [
            {
              "source": "longest_pm_stats_calculator_api_definition_post_endpoint_duration"
            }
          ]
        },
        {
          "_id": "longest_pm_stats_calculator_api_definition_delete_endpoint_duration",
          "widgetType": "timeline",
          "title": "Max KPI DELETE endpoint duration",
          "unit": "milliseconds",
          "sources": [
            {
              "source": "longest_pm_stats_calculator_api_definition_delete_endpoint_duration"
            }
          ]
        },
        {
          "_id": "longest_pm_stats_calculator_api_definition_patch_endpoint_duration",
          "widgetType": "timeline",
          "title": "Max KPI PATCH endpoint duration",
          "unit": "milliseconds",
          "sources": [
            {
              "source": "longest_pm_stats_calculator_api_definition_patch_endpoint_duration"
            }
          ]
        },
        {
          "_id": "longest_pm_stats_calculator_api_definition_get_endpoint_duration",
          "widgetType": "timeline",
          "title": "Max KPI GET endpoint duration",
          "unit": "milliseconds",
          "sources": [
            {
              "source": "longest_pm_stats_calculator_api_definition_get_endpoint_duration"
            }
          ]
        },
        {
          "_id": "widget_timeline_http_server_requests_seconds_count",
          "widgetType": "timeline",
          "title": "HTTP Server Requests Count",
          "sources": [{ "source": "source_http_server_requests_seconds_count" }]
        },
        {
          "_id": "widget_timeline_http_server_requests_seconds_max",
          "widgetType": "timeline",
          "title": "HTTP Server Requests Max",
          "unit": "sec",
          "sources": [{"source": "source_http_server_requests_seconds_max"}]
        },
        {
          "_id": "widget_timeline_http_server_requests_seconds_sum",
          "widgetType": "timeline",
          "title": "HTTP Server Requests Sum",
          "unit": "sec",
          "sources": [{"source": "source_http_server_requests_seconds_sum"}]
        }
      ],
      "sources": [
        {
          "_id": "avg_http_response_latency",
          "sourceType": "prometheus",
          "query": "sum by ({{ $podLabel }}) ((pm_stats_calculator_api_definition_post_endpoint_duration_ms_mean{app='{{ $calculatorName }}', job=~'kubernetes-pods.*', app_kubernetes_io_instance='{{ .Release.Name }}'} + pm_stats_calculator_api_definition_patch_endpoint_duration_ms_mean{app='{{ $calculatorName }}', job=~'kubernetes-pods.*', app_kubernetes_io_instance='{{ .Release.Name }}'} + pm_stats_calculator_api_definition_delete_endpoint_duration_ms_mean{app='{{ $calculatorName }}', job=~'kubernetes-pods.*', app_kubernetes_io_instance='{{ .Release.Name }}'} + pm_stats_calculator_api_definition_get_endpoint_duration_ms_mean{app='{{ $calculatorName }}', job=~'kubernetes-pods.*', app_kubernetes_io_instance='{{ .Release.Name }}'}) / (pm_stats_calculator_api_definition_post_endpoint_duration_ms_count{app='{{ $calculatorName }}', job=~'kubernetes-pods.*', app_kubernetes_io_instance='{{ .Release.Name }}'} + pm_stats_calculator_api_definition_patch_endpoint_duration_ms_count{app='{{ $calculatorName }}', job=~'kubernetes-pods.*', app_kubernetes_io_instance='{{ .Release.Name }}'} + pm_stats_calculator_api_definition_delete_endpoint_duration_ms_count{app='{{ $calculatorName }}', job=~'kubernetes-pods.*', app_kubernetes_io_instance='{{ .Release.Name }}'} + pm_stats_calculator_api_definition_get_endpoint_duration_ms_count{app='{{ $calculatorName }}', job=~'kubernetes-pods.*', app_kubernetes_io_instance='{{ .Release.Name }}'}))",
          "splitByLabelName": "{{ $podLabel }}"
        },
        {
          "_id": "longest_http_response_latency",
          "sourceType": "prometheus",
          "query": "max(max_over_time(pm_stats_calculator_api_definition_post_endpoint_duration_ms_max{app='{{ $calculatorName }}', job=~'kubernetes-pods.*', app_kubernetes_io_instance='{{ .Release.Name }}'}[1m]) or max_over_time(pm_stats_calculator_api_definition_patch_endpoint_duration_ms_max{app='{{ $calculatorName }}', job=~'kubernetes-pods.*', app_kubernetes_io_instance='{{ .Release.Name }}'}[1m]) or max_over_time(pm_stats_calculator_api_definition_delete_endpoint_duration_ms_max{app='{{ $calculatorName }}', job=~'kubernetes-pods.*', app_kubernetes_io_instance='{{ .Release.Name }}'}[1m]) or max_over_time(pm_stats_calculator_api_definition_get_endpoint_duration_ms_max{app='{{ $calculatorName }}', job=~'kubernetes-pods.*', app_kubernetes_io_instance='{{ .Release.Name }}'}[1m])) by ({{ $podLabel }})",
          "splitByLabelName": "{{ $podLabel }}"
        },
        {
          "_id": "longest_pm_stats_calculator_api_definition_post_endpoint_duration",
          "sourceType": "prometheus",
          "query": "max_over_time(pm_stats_calculator_api_definition_post_endpoint_duration_ms_max{app='{{ $calculatorName }}', job=~'kubernetes-pods.*', app_kubernetes_io_instance='{{ .Release.Name }}'}[1m])",
          "splitByLabelName": "{{ $podLabel }}"
        },
        {
          "_id": "longest_pm_stats_calculator_api_definition_delete_endpoint_duration",
          "sourceType": "prometheus",
          "query": "max_over_time(pm_stats_calculator_api_definition_delete_endpoint_duration_ms_max{app='{{ $calculatorName }}', job=~'kubernetes-pods.*', app_kubernetes_io_instance='{{ .Release.Name }}'}[1m])",
          "splitByLabelName": "{{ $podLabel }}"
        },
        {
          "_id": "longest_pm_stats_calculator_api_definition_patch_endpoint_duration",
          "sourceType": "prometheus",
          "query": "max_over_time(pm_stats_calculator_api_definition_patch_endpoint_duration_ms_max{app='{{ $calculatorName }}', job=~'kubernetes-pods.*', app_kubernetes_io_instance='{{ .Release.Name }}'}[1m])",
          "splitByLabelName": "{{ $podLabel }}"
        },
        {
          "_id": "longest_pm_stats_calculator_api_definition_get_endpoint_duration",
          "sourceType": "prometheus",
          "query": "max_over_time(pm_stats_calculator_api_definition_get_endpoint_duration_ms_max{app='{{ $calculatorName }}', job=~'kubernetes-pods.*', app_kubernetes_io_instance='{{ .Release.Name }}'}[1m])",
          "splitByLabelName": "{{ $podLabel }}"
        },
        {
          "_id": "source_http_server_requests_seconds_count",
          "sourceType": "prometheus",
          "query": "sum by ({{ $podLabel }}) (http_server_requests_seconds_count{{ print "{" }}{{ $podLabel }}=~'eric-oss-pm-stats-calculator.*'})",
          "splitByLabelName": "{{ $podLabel }}"
        },
        {
          "_id": "source_http_server_requests_seconds_max",
          "sourceType": "prometheus",
          "query": "sum by ({{ $podLabel }}) (http_server_requests_seconds_max{{ print "{" }}{{ $podLabel }}=~'eric-oss-pm-stats-calculator.*'})",
          "splitByLabelName": "{{ $podLabel }}"
        },
        {
          "_id": "source_http_server_requests_seconds_sum",
          "sourceType": "prometheus",
          "query": "sum by ({{ $podLabel }}) (http_server_requests_seconds_sum{{ print "{" }}{{ $podLabel }}=~'eric-oss-pm-stats-calculator.*'})",
          "splitByLabelName": "{{ $podLabel }}"
        }
      ]
    }
{{- end }}
