#
# COPYRIGHT Ericsson 2023
#
# The copyright to the computer program(s) herein is the property of
# Ericsson Inc. The programs may be used and/or copied only with written
# permission from Ericsson Inc. or in accordance with the terms and
# conditions stipulated in the agreement/contract under which the
# program(s) have been supplied.
#

{{- $global := fromJson (include "eric-oss-pm-stats-calculator.global" .) -}}
{{- if $global.securityPolicy.rolekind }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "eric-oss-pm-stats-calculator.securityPolicy.rolebindingName" . }}
  labels:
    {{- include "eric-oss-pm-stats-calculator.labels" . | nindent 4 }}
  annotations:
    {{- include "eric-oss-pm-stats-calculator.annotations" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: {{ template "eric-oss-pm-stats-calculator.securityPolicy.rolekind" . }}
  name: {{ template "eric-oss-pm-stats-calculator.securityPolicy.rolename" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "eric-oss-pm-stats-calculator.serviceAccountName" . }}
{{- end -}}