/*******************************************************************************
 * COPYRIGHT Ericsson 2024
 *
 * The copyright to the computer program(s) herein is the property of
 * Ericsson Inc. The programs may be used and/or copied only with written
 * permission from Ericsson Inc. or in accordance with the terms and
 * conditions stipulated in the agreement/contract under which the
 * program(s) have been supplied.
 ******************************************************************************/

package com.ericsson.oss.air.pm.stats.service.validator.sql;

import java.util.Set;

import lombok.NoArgsConstructor;

// TODO: refactor this class shouldn't exist, whitelist should come from an external source, such as k8s secret, configmap, pgsql table, etc.
@NoArgsConstructor(access = lombok.AccessLevel.PRIVATE)
public final class SqlWhitelist {
    public static final Set<String> ELEMENTS = Set.of(
            // Built-in functions
            "abs",
            "aggregate",
            "any",
            "array",
            "array_max",
            "array_min",
            "array_size",
            "array_sort",
            "avg",
            "bool_and",
            "bool_or",
            "cardinality",
            "cast",
            "ceil",
            "ceiling",
            "coalesce",
            "collect_list",
            "concat",
            "count",
            "date_add",
            "date_part",
            "date_trunc",
            "datediff",
            "day",
            "dayofmonth",
            "dayofweek",
            "dayofyear",
            "double",
            "every",
            "extract",
            "first",
            "floor",
            "greatest",
            "hour",
            "if",
            "ifnull",
            "in",
            "isnan",
            "isnotnull",
            "isnull",
            "last",
            "last_day",
            "least",
            "ln",
            "log",
            "log10",
            "max",
            "mean",
            "min",
            "minute",
            "mod",
            "month",
            "months_between",
            "nanvl",
            "negative",
            "next_day",
            "not",
            "nullif",
            "nvl",
            "nvl2",
            "positive",
            "quarter",
            "round",
            "second",
            "slice",
            "some",
            "sort_array",
            "substr",
            "substring",
            "sum",
            "to_timestamp",
            "trim",
            "weekday",
            "weekofyear",
            "year",
            "zip_with",

            // UDFs
            "add_long_to_array_with_limit",
            "add_double_to_array_with_limit",
            "add_integer_to_array_with_limit",
            "append_double_array_given_cardinality_and_limit",
            "append_integer_array_given_cardinality_and_limit",
            "append_long_array_given_cardinality_and_limit",
            "append_integer_array",
            "append_long_array",
            "array_index_sum",
            "array_index_sum_integer",
            "array_index_sum_double",
            "array_index_sum_long",
            "calculate_percentile_bin",
            "calculate_percentile_value",
            "calculate_weighted_average",
            "fdn_parse",
            "median_of_values",
            "percentile_index_80",
            "percentile_index_90",
            "update_null_time_advanced_kpis",

            // SQL CLAUSES - SOME COMES FROM CLASS NAME, THUS IT'S NOT HERE
            "!",
            "!=",
            "-",
            "%",
            "&",
            "*",
            "/",
            "^",
            "+",
            "<",
            "<=",
            "<=>",
            "<>",
            "=",
            "==",
            ">",
            ">=",
            "and",
            "as int",
            "as",
            "case when",
            "div",
            "from",
            "join",
            "or",
            "transform",
            "where"
    );
}
